
import { PRESETS } from "@/lib/schematic/tools";
import { nextLogId, now } from "./shared";
import { loadTeacherLock } from "@/lib/teacher";
import type { EditorData } from "./types";

export const initialState: EditorData = {
  doc: PRESETS[2].build(),
  selection: [],
  hoverNet: null,
  tool: "select",
  placingPartId: null,
  placingPreset: null,
  placingRot: 0,
  placingMirror: false,
  view: { x: 60, y: 20, zoom: 1 },
  theme: "system",
  uiFontSize: "standard",
  symbolStyle: "auto",
  showGrid: true,
  snap: true,
  autoRoute: true,
  showCurrentFlow: false,
  showVoltageColors: false,
  currentFlowDirection: "electron",
  showInlineValues: false,
  showRulers: false,
  showPageFrame: false,
  showErcMarkers: true,
  showRated: true,
  netResult: { netlist: { devices: [] }, nets: [], pinNets: {}, pointNets: {}, errors: [], warnings: [], openEnds: [], junctions: [] },
  past: [],
  future: [],
  logs: [
    { id: nextLogId(), level: "ok", time: now(), message: "Multispice bereit — MNA/Newton-Raphson-Kernel initialisiert." },
    { id: nextLogId(), level: "info", time: now(), message: "Beispielschaltung »555 Blinker« geladen. Drücke ▶ für die Echtzeitsimulation." },
  ],
  bottomTab: "console",
  bottomOpen: false,
  leftOpen: false,
  rightOpen: false,
  libraryOpen: false,
  libraryPos: { x: 24, y: 80 },
  librarySize: { w: 860, h: 560 },
  instruments: [],
  lastSavedAt: null,
  savePending: false,
  saveHealth: { local: "ok", file: "none" },
  probes: [],
  analysis: { kind: "", running: false },
  sim: { running: false, timeScale: 1, sampleRate: 200000, method: "trap", temperature: 27, tick: 0, fps: 0 },
  favorites: ["resistor", "capacitor", "led", "npn_2n3904", "opamp_lm741", "ne555"],
  recent: [],
  clipboard: null,
  toast: null,
  teacher: loadTeacherLock(),
  placingProbeKind: null,
  leadArmed: null,
  configArchive: {},
  spotlight: null,
  extractIds: null,
};
